# Generated by Django 4.1.4 on 2022-12-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_area', to='hotel.location'),
        ),
    ]
