# Generated by Django 4.1.4 on 2022-12-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_roomtype_hotel_hoteltype_room_attached_bathroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
