# Generated by Django 4.1.4 on 2022-12-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in',
            field=models.DateField(default='2022-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.DateField(default='2023-01-05'),
            preserve_default=False,
        ),
    ]
